version: '3.8'

services:
  bzd-taper-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/medications"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 